[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
remappings = ["@uniswap/v4-core/=lib/v4-core/", "solmate/=lib/solmate/"]

[profile.default.fuzz]
runs = 256
